### ISSUE TITLE
JSON Structure Representation

### ISSUE THREAD

**Issue by gregorymcdonald** [datafiniti/DataFizz#18]
The provided example JSON document for our solution represents an object with a named fields that contain the packed boxes. Is this the only allowed format for the solution's generated JSON file, or could my solution represent the packed boxes as an array of boxes without the boxes being named fields?

This representation would look similar to:
[
  {
    "id": 1,
    "totalWeight": 4.4,
    "contents": [
      {
        "title": "Zealot: The Life and Times of Jesus of Nazareth",
        "author": "Reza Aslan",
        "price": "$16.89 USD",
        "shipping_weight": "1.2 pounds",
        "isbn10": 140006922
      },
      {
        "title": "Pacific Rim: Man, Machines, and Monsters",
        "author": "David S Cohen, Guillermo del Toro",
        "price": "$27.83 USD",
        "shipping_weight": "3.2 pounds",
        "isbn10": 1608871827
      }
    ]
  },

...

**Comment by shiondev** [comment]
Hi Greg - That representation is fine.

On Thu, May 7, 2015 at 12:14 AM, Greg McDonald <notifications@github.com>
wrote:

> The provided example JSON document for our solution represents an object
> with a named fields that contain the packed boxes. Is this the only allowed
> format for the solution's generated JSON file, or could my solution
> represent the packed boxes as an array of boxes without the boxes being
> named fields?
>
> This representation would look similar to:
> [
> {
> "id": 1,
> "totalWeight": 4.4,
> "contents": [
> {
> "title": "Zealot: The Life and Times of Jesus of Nazareth",
> "author": "Reza Aslan",
> "price": "$16.89 USD",
> "shipping_weight": "1.2 pounds",
> "isbn10": 140006922
> },
> {
> "title": "Pacific Rim: Man, Machines, and Monsters",
> "author": "David S Cohen, Guillermo del Toro",
> "price": "$27.83 USD",
> "shipping_weight": "3.2 pounds",
> "isbn10": 1608871827
> }
> ]
> },
>
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datafiniti/DataFizz/issues/18>.
>



-- 
Shion Deysarkar
CEO & Founder
Datafiniti | Open Access to Web Data
http://www.datafiniti.co
